// AUTO-GENERATED by pbuilder-codegen — do not edit. Regenerate: pbuilder-codegen <package-dir>
// @schema-digest sha256:ae66211ea84c4dbfc5ab6b58c8afd067cb1fbd62b230f5826fb5bdce87b3f899

export type Input = {
  /** Entity name */
  name: string;
  /** Include generated tests */
  withTests?: boolean;
  /** Module visibility */
  visibility?: "public" | "internal";
};
