// AUTO-GENERATED by pbuilder-codegen — do not edit. Regenerate: pbuilder-codegen <package-dir>
// @schema-digest sha256:ab18b93faf45647a7d5771819ac25660b27a173c6ee4690fb9d1af331aaaa7de

export type Input = {
  /** Server port */
  port: number;
};
