// AUTO-GENERATED by pbuilder-codegen — do not edit. Regenerate: pbuilder-codegen <package-dir>
// @schema-digest sha256:0000000000000000000000000000000000000000000000000000000000000000
//
// DELIBERATELY STALE (test/fixtures/red/**, never walked by the always-on FIT-12 gate —
// design §4.6a). The embedded digest above deliberately does NOT match the adjacent
// schema.json's actual digest — FIT-12's staled-digest red-proof drives its check function
// directly against this fixture (REQ-SCP-01.1).

export type Input = {
  /** Server port */
  port: number;
};
