// AUTO-GENERATED by pbuilder-codegen — do not edit. Regenerate: pbuilder-codegen <package-dir>
// @schema-digest sha256:b9d417420856d234c471f597a749193b6135259112a95746cdf2706c5d6b93d0
//
// DELIBERATELY STALE (test/fixtures/red/**, never walked — design §4.6a). Committed against
// the ORIGINAL schema.json (whose "port" property carried the label "Old label"); the
// adjacent schema.json has since been edited to "New label" WITHOUT regenerating. Proves
// REQ-SCP-01.3: a label-only edit — no TypeScript-visible type-shape change — still stales
// the digest, because the gate compares the SOURCE schema.json bytes, not the compiled type
// text (which would be identical either way).

export type Input = {
  /** Old label */
  port: number;
};
